### ISSUE TITLE
Add a preview window

### ISSUE THREAD

**Issue by ANISH0309** [ACM-VIT/maildart-frontend#13]
- Include a preview window that shows the rendered email body output.
- The output should be rendered HTML (if the input of the email body is in HTML) and not in plain text.

refer to the wireframe(mentioned in the [notion guide](https://grass-text-1a7.notion.site/Maildart-Frontend-5ea6f3ea336a487da18cd2a99a21a213)) and size the preview window accordingly

**Comment by Rachel-glitch** [comment]
Assign this issue to me please.

**Comment by ANISH0309** [comment]
> Assign this issue to me please.

Sure, assigning you this issue.
