### ISSUE TITLE
Create radio buttons using react hooks

### ISSUE THREAD

**Issue by ANISH0309** [ACM-VIT/maildart-frontend#7]
- user will have 4 options to choose the mailing service:
  -  listmonk 
  - Nodemailer
  - Mailgun 
  - SendGrid

**Comment by ayushgoswamiabr** [comment]
I would like to work on this

**Comment by ayushgoswamiabr** [comment]
I have opened a Pull Request #12

**Comment by ANISH0309** [comment]
> I would like to work on this

Hey, assigning you this issue.

**Comment by ayushgoswamiabr** [comment]
I have committed the requested changes
