### ISSUE TITLE
Create input fields using react hooks

### ISSUE THREAD

**Issue by ANISH0309** [ACM-VIT/maildart-frontend#8]
Input fields should be created for:
- email subject
- authkey/credentials
- an option to choose a CSV file

**Comment by MuhammadTanveer94** [comment]
@ANISH0309 i would love to work on this.

**Comment by ANISH0309** [comment]
> @ANISH0309 i would love to work on this.

Hey, assigning you this issue.

**Comment by ANISH0309** [comment]
Hey @MuhammadTanveer94, can you please update me about your progress?

**Comment by satyamsingh07** [comment]
@ANISH0309 could you assign me this issue?thanks

**Comment by satyamsingh07** [comment]
@ANISH0309 bhaiya i'm done with my previous issue, so could I take over now.

**Comment by ANISH0309** [comment]
> @ANISH0309 bhaiya i'm done with my previous issue, so could I take over now.

Alright! Go ahead with this issue. Good luck.
