### ISSUE TITLE
Create a textarea using react hooks

### ISSUE THREAD

**Issue by ANISH0309** [ACM-VIT/maildart-frontend#9]
- Textarea should be created for email body

refer to the wireframe(mentioned in the [notion guide](https://grass-text-1a7.notion.site/Maildart-9dec4c315dcf407fa73d06a3023edc6c)) and size it accordingly

**Comment by faisaljamil25** [comment]
@Avinaash7 can I work on this?

**Comment by MuhammadTanveer94** [comment]
@ANISH0309  could you please assign me?

**Comment by ANISH0309** [comment]
> @Avinaash7 can I work on this?

Hey, assigning you this issue.

**Comment by ANISH0309** [comment]
> @ANISH0309 could you please assign me?

Hey @MuhammadTanveer94, wanna work on this issue?

**Comment by satyamsingh07** [comment]
Hey,could you please assign me this issue?

**Comment by ANISH0309** [comment]
> Hey,could you please assign me this issue?

Alright, assigning you this issue.
